eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8081/eureka/,http://eureka2:8082/eureka/
    fetchRegistry: true
    registerWithEureka: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,routes,refresh
server:
  port: 6001